# Generated by Django 2.2.3 on 2020-07-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestmodel',
            name='email',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
