# Generated by Django 2.2 on 2021-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_marksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertestmodel',
            name='email',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='usertestmodel',
            unique_together={('subject', 'email')},
        ),
    ]
