# Generated by Django 2.2 on 2021-06-10 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210610_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marksmodel',
            unique_together={('subject', 'email')},
        ),
    ]
