# Generated by Django 5.1.4 on 2025-01-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210610_1638'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marksmodel',
            unique_together=set(),
        ),
    ]
